/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Gestion_foyer (void)
{
  GtkWidget *Gestion_foyer;
  GtkWidget *fixed4;
  GtkWidget *notebook3;
  GtkWidget *fixed12;
  GtkWidget *entry10;
  GtkWidget *entry11;
  GtkWidget *entry12;
  GtkWidget *entry13;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkWidget *entry14;
  GtkWidget *label279;
  GtkWidget *label337;
  GtkWidget *ajou_ch;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label59;
  GtkWidget *button9;
  GtkWidget *alignment76;
  GtkWidget *hbox76;
  GtkWidget *image82;
  GtkWidget *label320;
  GtkWidget *combobox6;
  GtkWidget *button7;
  GtkWidget *alignment78;
  GtkWidget *hbox78;
  GtkWidget *image85;
  GtkWidget *label357;
  GtkWidget *label333;
  GtkWidget *button8;
  GtkWidget *alignment80;
  GtkWidget *hbox80;
  GtkWidget *image87;
  GtkWidget *label359;
  GtkWidget *button13;
  GtkWidget *alignment81;
  GtkWidget *hbox81;
  GtkWidget *image88;
  GtkWidget *label360;
  GtkWidget *label334;
  GtkWidget *button10;
  GtkWidget *alignment79;
  GtkWidget *hbox79;
  GtkWidget *image86;
  GtkWidget *label358;
  GtkWidget *button12;
  GtkWidget *alignment83;
  GtkWidget *hbox83;
  GtkWidget *image90;
  GtkWidget *label362;
  GtkWidget *label338;
  GtkWidget *label335;
  GtkWidget *button11;
  GtkWidget *alignment82;
  GtkWidget *hbox82;
  GtkWidget *image89;
  GtkWidget *label361;
  GtkWidget *label336;
  GtkWidget *button17;
  GtkWidget *alignment84;
  GtkWidget *hbox84;
  GtkWidget *image91;
  GtkWidget *label363;
  GtkWidget *button14;
  GtkWidget *button15;
  GtkWidget *button16;
  GtkWidget *calendar1;
  GtkWidget *button19;
  GtkWidget *button18;
  GtkWidget *button5_ok_;
  GtkWidget *alignment59;
  GtkWidget *hbox59;
  GtkWidget *image62;
  GtkWidget *label237;
  GtkWidget *radiobutton12_poste;
  GSList *radiobutton12_poste_group = NULL;
  GtkWidget *radiobutton11_poste;
  GtkWidget *checkbutton15_groupe;
  GtkWidget *checkbutton14_groupe;
  GtkWidget *label364;
  GtkWidget *fixed13;
  GtkWidget *entry15;
  GtkWidget *label83;
  GtkWidget *supp_ch;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label61;
  GtkWidget *label332;
  GtkWidget *button20;
  GtkWidget *alignment77;
  GtkWidget *hbox77;
  GtkWidget *image84;
  GtkWidget *label331;
  GtkWidget *label365;
  GtkWidget *fixed14;
  GtkWidget *entry16;
  GtkWidget *entry17;
  GtkWidget *entry18;
  GtkWidget *entry19;
  GtkWidget *entry20;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkWidget *entry21;
  GtkWidget *label84;
  GtkWidget *label317;
  GtkWidget *modi_ch;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label78;
  GtkWidget *button45;
  GtkWidget *rech_ch;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label64;
  GtkWidget *button53;
  GtkWidget *button52;
  GtkWidget *label354;
  GtkWidget *label355;
  GtkWidget *combobox7;
  GtkWidget *button49;
  GtkWidget *alignment85;
  GtkWidget *hbox85;
  GtkWidget *image95;
  GtkWidget *label376;
  GtkWidget *button51;
  GtkWidget *alignment86;
  GtkWidget *hbox86;
  GtkWidget *image96;
  GtkWidget *label377;
  GtkWidget *button48;
  GtkWidget *alignment87;
  GtkWidget *hbox87;
  GtkWidget *image97;
  GtkWidget *label378;
  GtkWidget *button46;
  GtkWidget *alignment88;
  GtkWidget *hbox88;
  GtkWidget *image98;
  GtkWidget *label382;
  GtkWidget *button50;
  GtkWidget *alignment90;
  GtkWidget *hbox90;
  GtkWidget *image100;
  GtkWidget *label380;
  GtkWidget *button55;
  GtkWidget *alignment91;
  GtkWidget *hbox91;
  GtkWidget *image101;
  GtkWidget *label381;
  GtkWidget *button54;
  GtkWidget *alignment92;
  GtkWidget *hbox92;
  GtkWidget *image102;
  GtkWidget *label375;
  GtkWidget *label379;
  GtkWidget *label366;
  GtkWidget *fixed15;
  GtkWidget *treeview5;
  GtkWidget *label238;
  GtkWidget *modifier_ch;
  GtkWidget *alignment50;
  GtkWidget *hbox50;
  GtkWidget *image53;
  GtkWidget *label210;
  GtkWidget *supp_tree_ch;
  GtkWidget *alignment51;
  GtkWidget *hbox51;
  GtkWidget *image54;
  GtkWidget *label211;
  GtkWidget *label356;
  GtkWidget *label367;
  GtkWidget *fixed16;
  GtkWidget *treeview6;
  GtkWidget *button56;
  GtkWidget *button57;
  GtkWidget *label383;
  GtkWidget *buttonMaps;
  GtkWidget *alignment93;
  GtkWidget *hbox93;
  GtkWidget *image103;
  GtkWidget *label384;
  GtkWidget *buttonINST;
  GtkWidget *image94;
  GtkWidget *buttonFB;
  GtkWidget *image93;
  GtkWidget *image104;
  GtkWidget *image92;

  Gestion_foyer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_foyer), _("Gestion Foyer"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Gestion_foyer), fixed4);

  notebook3 = gtk_notebook_new ();
  gtk_widget_show (notebook3);
  gtk_fixed_put (GTK_FIXED (fixed4), notebook3, 32, 168);
  gtk_widget_set_size_request (notebook3, 1080, 600);
  GTK_WIDGET_UNSET_FLAGS (notebook3, GTK_CAN_FOCUS);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed12);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed12), entry10, 112, 96);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed12), entry11, 464, 96);
  gtk_widget_set_size_request (entry11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed12), entry12, 112, 224);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed12), entry13, 160, 296);
  gtk_widget_set_size_request (entry13, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton2, 496, 240);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton3, 504, 272);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  spinbutton4_adj = gtk_adjustment_new (2020, 2020, 2050, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton4, 504, 304);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed12), entry14, 464, 144);
  gtk_widget_set_size_request (entry14, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  label279 = gtk_label_new ("");
  gtk_widget_show (label279);
  gtk_fixed_put (GTK_FIXED (fixed12), label279, 600, 280);
  gtk_widget_set_size_request (label279, 89, 25);

  label337 = gtk_label_new ("");
  gtk_widget_show (label337);
  gtk_fixed_put (GTK_FIXED (fixed12), label337, 0, 0);
  gtk_widget_set_size_request (label337, 0, 0);

  ajou_ch = gtk_button_new ();
  gtk_widget_show (ajou_ch);
  gtk_fixed_put (GTK_FIXED (fixed12), ajou_ch, 352, 432);
  gtk_widget_set_size_request (ajou_ch, 130, 45);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (ajou_ch), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("Ajouter "));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox12), label59, FALSE, FALSE, 0);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed12), button9, 304, 8);
  gtk_widget_set_size_request (button9, 280, 32);

  alignment76 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment76);
  gtk_container_add (GTK_CONTAINER (button9), alignment76);

  hbox76 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox76);
  gtk_container_add (GTK_CONTAINER (alignment76), hbox76);

  image82 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image82);
  gtk_box_pack_start (GTK_BOX (hbox76), image82, FALSE, FALSE, 0);

  label320 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\"> Merci de remplir ce formulaire : </span></b>"));
  gtk_widget_show (label320);
  gtk_box_pack_start (GTK_BOX (hbox76), label320, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label320), TRUE);

  combobox6 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox6);
  gtk_fixed_put (GTK_FIXED (fixed12), combobox6, 176, 144);
  gtk_widget_set_size_request (combobox6, 113, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Femme"));

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed12), button7, 8, 96);
  gtk_widget_set_size_request (button7, 82, 29);

  alignment78 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment78);
  gtk_container_add (GTK_CONTAINER (button7), alignment78);

  hbox78 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox78);
  gtk_container_add (GTK_CONTAINER (alignment78), hbox78);

  image85 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image85);
  gtk_box_pack_start (GTK_BOX (hbox78), image85, FALSE, FALSE, 0);

  label357 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Nom </span></b>"));
  gtk_widget_show (label357);
  gtk_box_pack_start (GTK_BOX (hbox78), label357, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label357), TRUE);

  label333 = gtk_label_new ("");
  gtk_widget_show (label333);
  gtk_fixed_put (GTK_FIXED (fixed12), label333, 144, 56);
  gtk_widget_set_size_request (label333, 145, 33);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed12), button8, 8, 144);
  gtk_widget_set_size_request (button8, 150, 29);

  alignment80 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment80);
  gtk_container_add (GTK_CONTAINER (button8), alignment80);

  hbox80 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox80);
  gtk_container_add (GTK_CONTAINER (alignment80), hbox80);

  image87 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image87);
  gtk_box_pack_start (GTK_BOX (hbox80), image87, FALSE, FALSE, 0);

  label359 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Sexe </span></b>"));
  gtk_widget_show (label359);
  gtk_box_pack_start (GTK_BOX (hbox80), label359, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label359), TRUE);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed12), button13, 360, 208);
  gtk_widget_set_size_request (button13, 200, 29);

  alignment81 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment81);
  gtk_container_add (GTK_CONTAINER (button13), alignment81);

  hbox81 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox81);
  gtk_container_add (GTK_CONTAINER (alignment81), hbox81);

  image88 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image88);
  gtk_box_pack_start (GTK_BOX (hbox81), image88, FALSE, FALSE, 0);

  label360 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Date de naissance </span></b>"));
  gtk_widget_show (label360);
  gtk_box_pack_start (GTK_BOX (hbox81), label360, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label360), TRUE);

  label334 = gtk_label_new ("");
  gtk_widget_show (label334);
  gtk_fixed_put (GTK_FIXED (fixed12), label334, 480, 64);
  gtk_widget_set_size_request (label334, 192, 25);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed12), button10, 344, 96);
  gtk_widget_set_size_request (button10, 98, 29);

  alignment79 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment79);
  gtk_container_add (GTK_CONTAINER (button10), alignment79);

  hbox79 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox79);
  gtk_container_add (GTK_CONTAINER (alignment79), hbox79);

  image86 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image86);
  gtk_box_pack_start (GTK_BOX (hbox79), image86, FALSE, FALSE, 0);

  label358 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Pr\303\251nom </span></b>"));
  gtk_widget_show (label358);
  gtk_box_pack_start (GTK_BOX (hbox79), label358, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label358), TRUE);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed12), button12, 352, 144);
  gtk_widget_set_size_request (button12, 98, 29);

  alignment83 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment83);
  gtk_container_add (GTK_CONTAINER (button12), alignment83);

  hbox83 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox83);
  gtk_container_add (GTK_CONTAINER (alignment83), hbox83);

  image90 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image90);
  gtk_box_pack_start (GTK_BOX (hbox83), image90, FALSE, FALSE, 0);

  label362 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Chambre </span></b>"));
  gtk_widget_show (label362);
  gtk_box_pack_start (GTK_BOX (hbox83), label362, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label362), TRUE);

  label338 = gtk_label_new ("");
  gtk_widget_show (label338);
  gtk_fixed_put (GTK_FIXED (fixed12), label338, 416, 176);
  gtk_widget_set_size_request (label338, 201, 33);

  label335 = gtk_label_new ("");
  gtk_widget_show (label335);
  gtk_fixed_put (GTK_FIXED (fixed12), label335, 160, 176);
  gtk_widget_set_size_request (label335, 145, 33);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed12), button11, 32, 224);
  gtk_widget_set_size_request (button11, 74, 29);

  alignment82 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment82);
  gtk_container_add (GTK_CONTAINER (button11), alignment82);

  hbox82 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox82);
  gtk_container_add (GTK_CONTAINER (alignment82), hbox82);

  image89 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image89);
  gtk_box_pack_start (GTK_BOX (hbox82), image89, FALSE, FALSE, 0);

  label361 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Mail </span></b>"));
  gtk_widget_show (label361);
  gtk_box_pack_start (GTK_BOX (hbox82), label361, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label361), TRUE);

  label336 = gtk_label_new ("");
  gtk_widget_show (label336);
  gtk_fixed_put (GTK_FIXED (fixed12), label336, 120, 256);
  gtk_widget_set_size_request (label336, 145, 33);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed12), button17, 24, 296);
  gtk_widget_set_size_request (button17, 130, 29);

  alignment84 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment84);
  gtk_container_add (GTK_CONTAINER (button17), alignment84);

  hbox84 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox84);
  gtk_container_add (GTK_CONTAINER (alignment84), hbox84);

  image91 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image91);
  gtk_box_pack_start (GTK_BOX (hbox84), image91, FALSE, FALSE, 0);

  label363 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> T\303\251l </span></b>"));
  gtk_widget_show (label363);
  gtk_box_pack_start (GTK_BOX (hbox84), label363, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label363), TRUE);

  button14 = gtk_button_new_with_mnemonic (_("Jour : "));
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed12), button14, 392, 240);
  gtk_widget_set_size_request (button14, 74, 29);

  button15 = gtk_button_new_with_mnemonic (_("Mois :"));
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed12), button15, 392, 272);
  gtk_widget_set_size_request (button15, 74, 29);

  button16 = gtk_button_new_with_mnemonic (_("Ann\303\251e :"));
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed12), button16, 392, 304);
  gtk_widget_set_size_request (button16, 74, 29);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed12), calendar1, 904, 8);
  gtk_widget_set_size_request (calendar1, 162, 186);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  button19 = gtk_button_new_with_mnemonic (_("Poste :"));
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed12), button19, 680, 312);
  gtk_widget_set_size_request (button19, 96, 29);

  button18 = gtk_button_new_with_mnemonic (_("Groupes : "));
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed12), button18, 680, 224);
  gtk_widget_set_size_request (button18, 98, 29);

  button5_ok_ = gtk_button_new ();
  gtk_widget_show (button5_ok_);
  gtk_fixed_put (GTK_FIXED (fixed12), button5_ok_, 928, 280);
  gtk_widget_set_size_request (button5_ok_, 106, 29);

  alignment59 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment59);
  gtk_container_add (GTK_CONTAINER (button5_ok_), alignment59);

  hbox59 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox59);
  gtk_container_add (GTK_CONTAINER (alignment59), hbox59);

  image62 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image62);
  gtk_box_pack_start (GTK_BOX (hbox59), image62, FALSE, FALSE, 0);

  label237 = gtk_label_new_with_mnemonic (_("OK "));
  gtk_widget_show (label237);
  gtk_box_pack_start (GTK_BOX (hbox59), label237, FALSE, FALSE, 0);

  radiobutton12_poste = gtk_radio_button_new_with_mnemonic (NULL, _("Bloc Homme"));
  gtk_widget_show (radiobutton12_poste);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton12_poste, 792, 312);
  gtk_widget_set_size_request (radiobutton12_poste, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton12_poste), radiobutton12_poste_group);
  radiobutton12_poste_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton12_poste));

  radiobutton11_poste = gtk_radio_button_new_with_mnemonic (NULL, _("Bloc Fille"));
  gtk_widget_show (radiobutton11_poste);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton11_poste, 792, 336);
  gtk_widget_set_size_request (radiobutton11_poste, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11_poste), radiobutton12_poste_group);
  radiobutton12_poste_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11_poste));

  checkbutton15_groupe = gtk_check_button_new_with_mnemonic (_("Groupe femme"));
  gtk_widget_show (checkbutton15_groupe);
  gtk_fixed_put (GTK_FIXED (fixed12), checkbutton15_groupe, 792, 256);
  gtk_widget_set_size_request (checkbutton15_groupe, 126, 24);

  checkbutton14_groupe = gtk_check_button_new_with_mnemonic (_("Groupe homme"));
  gtk_widget_show (checkbutton14_groupe);
  gtk_fixed_put (GTK_FIXED (fixed12), checkbutton14_groupe, 792, 224);
  gtk_widget_set_size_request (checkbutton14_groupe, 126, 24);

  label364 = gtk_label_new_with_mnemonic (_("<b><span color=\"blue\"> Ajouter </span></b>"));
  gtk_widget_show (label364);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 0), label364);
  gtk_label_set_use_markup (GTK_LABEL (label364), TRUE);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed13);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed13), entry15, 408, 88);
  gtk_widget_set_size_request (entry15, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  label83 = gtk_label_new ("");
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed13), label83, 376, 264);
  gtk_widget_set_size_request (label83, 281, 41);

  supp_ch = gtk_button_new ();
  gtk_widget_show (supp_ch);
  gtk_fixed_put (GTK_FIXED (fixed13), supp_ch, 496, 128);
  gtk_widget_set_size_request (supp_ch, 122, 37);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (supp_ch), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label61 = gtk_label_new_with_mnemonic (_("supprimer "));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox13), label61, FALSE, FALSE, 0);

  label332 = gtk_label_new (_("<b><span color=\"red\"> </span></b>"));
  gtk_widget_show (label332);
  gtk_fixed_put (GTK_FIXED (fixed13), label332, 584, 72);
  gtk_widget_set_size_request (label332, 289, 49);
  gtk_label_set_use_markup (GTK_LABEL (label332), TRUE);

  button20 = gtk_button_new ();
  gtk_widget_show (button20);
  gtk_fixed_put (GTK_FIXED (fixed13), button20, 288, 80);
  gtk_widget_set_size_request (button20, 114, 40);

  alignment77 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment77);
  gtk_container_add (GTK_CONTAINER (button20), alignment77);

  hbox77 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox77);
  gtk_container_add (GTK_CONTAINER (alignment77), hbox77);

  image84 = gtk_image_new_from_stock ("gtk-print-preview", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image84);
  gtk_box_pack_start (GTK_BOX (hbox77), image84, FALSE, FALSE, 0);

  label331 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\">  Saisir l'id  </span></b>"));
  gtk_widget_show (label331);
  gtk_box_pack_start (GTK_BOX (hbox77), label331, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label331), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label331), 0.5, 0.55);

  label365 = gtk_label_new_with_mnemonic (_("<b><span color=\"blue\"> Supprimer </span></b>"));
  gtk_widget_show (label365);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 1), label365);
  gtk_label_set_use_markup (GTK_LABEL (label365), TRUE);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed14);

  entry16 = gtk_entry_new ();
  gtk_widget_show (entry16);
  gtk_fixed_put (GTK_FIXED (fixed14), entry16, 280, 56);
  gtk_widget_set_size_request (entry16, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 8226);

  entry17 = gtk_entry_new ();
  gtk_widget_show (entry17);
  gtk_fixed_put (GTK_FIXED (fixed14), entry17, 224, 152);
  gtk_widget_set_size_request (entry17, 181, 29);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17), 8226);

  entry18 = gtk_entry_new ();
  gtk_widget_show (entry18);
  gtk_fixed_put (GTK_FIXED (fixed14), entry18, 816, 160);
  gtk_widget_set_size_request (entry18, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18), 8226);

  entry19 = gtk_entry_new ();
  gtk_widget_show (entry19);
  gtk_fixed_put (GTK_FIXED (fixed14), entry19, 240, 328);
  gtk_widget_set_size_request (entry19, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry19), 8226);

  entry20 = gtk_entry_new ();
  gtk_widget_show (entry20);
  gtk_fixed_put (GTK_FIXED (fixed14), entry20, 696, 384);
  gtk_widget_set_size_request (entry20, 168, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry20), 8226);

  spinbutton5_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbutton5, 312, 456);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbutton6, 528, 456);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  spinbutton7_adj = gtk_adjustment_new (1, 1960, 2050, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbutton7, 744, 456);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  entry21 = gtk_entry_new ();
  gtk_widget_show (entry21);
  gtk_fixed_put (GTK_FIXED (fixed14), entry21, 824, 312);
  gtk_widget_set_size_request (entry21, 184, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry21), 8226);

  label84 = gtk_label_new ("");
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed14), label84, 360, 96);
  gtk_widget_set_size_request (label84, 113, 25);

  label317 = gtk_label_new ("");
  gtk_widget_show (label317);
  gtk_fixed_put (GTK_FIXED (fixed14), label317, 472, 24);
  gtk_widget_set_size_request (label317, 208, 33);

  modi_ch = gtk_button_new ();
  gtk_widget_show (modi_ch);
  gtk_fixed_put (GTK_FIXED (fixed14), modi_ch, 600, 48);
  gtk_widget_set_size_request (modi_ch, 122, 37);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (modi_ch), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label78 = gtk_label_new_with_mnemonic (_("MODIFIER "));
  gtk_widget_show (label78);
  gtk_box_pack_start (GTK_BOX (hbox19), label78, FALSE, FALSE, 0);

  button45 = gtk_button_new_with_mnemonic (_("Passer votre ID : "));
  gtk_widget_show (button45);
  gtk_fixed_put (GTK_FIXED (fixed14), button45, 128, 48);
  gtk_widget_set_size_request (button45, 128, 37);

  rech_ch = gtk_button_new ();
  gtk_widget_show (rech_ch);
  gtk_fixed_put (GTK_FIXED (fixed14), rech_ch, 472, 48);
  gtk_widget_set_size_request (rech_ch, 112, 37);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (rech_ch), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label64 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox15), label64, FALSE, FALSE, 0);

  button53 = gtk_button_new_with_mnemonic (_("Mois :"));
  gtk_widget_show (button53);
  gtk_fixed_put (GTK_FIXED (fixed14), button53, 432, 456);
  gtk_widget_set_size_request (button53, 74, 29);

  button52 = gtk_button_new_with_mnemonic (_("Ann\303\251e :"));
  gtk_widget_show (button52);
  gtk_fixed_put (GTK_FIXED (fixed14), button52, 648, 456);
  gtk_widget_set_size_request (button52, 74, 29);

  label354 = gtk_label_new ("");
  gtk_widget_show (label354);
  gtk_fixed_put (GTK_FIXED (fixed14), label354, 176, 96);
  gtk_widget_set_size_request (label354, 241, 33);

  label355 = gtk_label_new ("");
  gtk_widget_show (label355);
  gtk_fixed_put (GTK_FIXED (fixed14), label355, 176, 264);
  gtk_widget_set_size_request (label355, 161, 25);

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_fixed_put (GTK_FIXED (fixed14), combobox7, 288, 216);
  gtk_widget_set_size_request (combobox7, 120, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Homme "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Femme"));

  button49 = gtk_button_new ();
  gtk_widget_show (button49);
  gtk_fixed_put (GTK_FIXED (fixed14), button49, 104, 144);
  gtk_widget_set_size_request (button49, 98, 37);

  alignment85 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment85);
  gtk_container_add (GTK_CONTAINER (button49), alignment85);

  hbox85 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox85);
  gtk_container_add (GTK_CONTAINER (alignment85), hbox85);

  image95 = gtk_image_new_from_stock ("gtk-revert-to-saved", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image95);
  gtk_box_pack_start (GTK_BOX (hbox85), image95, FALSE, FALSE, 0);

  label376 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Nom </span></b>"));
  gtk_widget_show (label376);
  gtk_box_pack_start (GTK_BOX (hbox85), label376, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label376), TRUE);

  button51 = gtk_button_new ();
  gtk_widget_show (button51);
  gtk_fixed_put (GTK_FIXED (fixed14), button51, 688, 152);
  gtk_widget_set_size_request (button51, 98, 37);

  alignment86 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment86);
  gtk_container_add (GTK_CONTAINER (button51), alignment86);

  hbox86 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox86);
  gtk_container_add (GTK_CONTAINER (alignment86), hbox86);

  image96 = gtk_image_new_from_stock ("gtk-network", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image96);
  gtk_box_pack_start (GTK_BOX (hbox86), image96, FALSE, FALSE, 0);

  label377 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Pr\303\251nom </span></b>"));
  gtk_widget_show (label377);
  gtk_box_pack_start (GTK_BOX (hbox86), label377, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label377), TRUE);

  button48 = gtk_button_new ();
  gtk_widget_show (button48);
  gtk_fixed_put (GTK_FIXED (fixed14), button48, 128, 216);
  gtk_widget_set_size_request (button48, 150, 29);

  alignment87 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment87);
  gtk_container_add (GTK_CONTAINER (button48), alignment87);

  hbox87 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox87);
  gtk_container_add (GTK_CONTAINER (alignment87), hbox87);

  image97 = gtk_image_new_from_stock ("gtk-revert-to-saved", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image97);
  gtk_box_pack_start (GTK_BOX (hbox87), image97, FALSE, FALSE, 0);

  label378 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Sexe </span></b>"));
  gtk_widget_show (label378);
  gtk_box_pack_start (GTK_BOX (hbox87), label378, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label378), TRUE);

  button46 = gtk_button_new ();
  gtk_widget_show (button46);
  gtk_fixed_put (GTK_FIXED (fixed14), button46, 608, 312);
  gtk_widget_set_size_request (button46, 194, 37);

  alignment88 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment88);
  gtk_container_add (GTK_CONTAINER (button46), alignment88);

  hbox88 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox88);
  gtk_container_add (GTK_CONTAINER (alignment88), hbox88);

  image98 = gtk_image_new_from_stock ("gtk-revert-to-saved", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image98);
  gtk_box_pack_start (GTK_BOX (hbox88), image98, FALSE, FALSE, 0);

  label382 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Chambre </span></b>"));
  gtk_widget_show (label382);
  gtk_box_pack_start (GTK_BOX (hbox88), label382, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label382), TRUE);

  button50 = gtk_button_new ();
  gtk_widget_show (button50);
  gtk_fixed_put (GTK_FIXED (fixed14), button50, 144, 408);
  gtk_widget_set_size_request (button50, 162, 29);

  alignment90 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment90);
  gtk_container_add (GTK_CONTAINER (button50), alignment90);

  hbox90 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox90);
  gtk_container_add (GTK_CONTAINER (alignment90), hbox90);

  image100 = gtk_image_new_from_stock ("gtk-revert-to-saved", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image100);
  gtk_box_pack_start (GTK_BOX (hbox90), image100, FALSE, FALSE, 0);

  label380 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Date de naissance </span></b>"));
  gtk_widget_show (label380);
  gtk_box_pack_start (GTK_BOX (hbox90), label380, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label380), TRUE);

  button55 = gtk_button_new ();
  gtk_widget_show (button55);
  gtk_fixed_put (GTK_FIXED (fixed14), button55, 528, 384);
  gtk_widget_set_size_request (button55, 162, 29);

  alignment91 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment91);
  gtk_container_add (GTK_CONTAINER (button55), alignment91);

  hbox91 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox91);
  gtk_container_add (GTK_CONTAINER (alignment91), hbox91);

  image101 = gtk_image_new_from_stock ("gtk-revert-to-saved", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image101);
  gtk_box_pack_start (GTK_BOX (hbox91), image101, FALSE, FALSE, 0);

  label381 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> T\303\251l </span></b>"));
  gtk_widget_show (label381);
  gtk_box_pack_start (GTK_BOX (hbox91), label381, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label381), TRUE);

  button54 = gtk_button_new ();
  gtk_widget_show (button54);
  gtk_fixed_put (GTK_FIXED (fixed14), button54, 224, 456);
  gtk_widget_set_size_request (button54, 74, 29);

  alignment92 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment92);
  gtk_container_add (GTK_CONTAINER (button54), alignment92);

  hbox92 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox92);
  gtk_container_add (GTK_CONTAINER (alignment92), hbox92);

  image102 = gtk_image_new_from_stock ("gtk-revert-to-saved", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image102);
  gtk_box_pack_start (GTK_BOX (hbox92), image102, FALSE, FALSE, 0);

  label375 = gtk_label_new_with_mnemonic (_("Jour :"));
  gtk_widget_show (label375);
  gtk_box_pack_start (GTK_BOX (hbox92), label375, FALSE, FALSE, 0);

  label379 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Mail </span></b>"));
  gtk_widget_show (label379);
  gtk_fixed_put (GTK_FIXED (fixed14), label379, 152, 328);
  gtk_widget_set_size_request (label379, 74, 29);
  gtk_label_set_use_markup (GTK_LABEL (label379), TRUE);

  label366 = gtk_label_new_with_mnemonic (_("<b><span color=\"blue\"> Chercher / Modifier</span></b>"));
  gtk_widget_show (label366);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 2), label366);
  gtk_label_set_use_markup (GTK_LABEL (label366), TRUE);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed15);

  treeview5 = gtk_tree_view_new ();
  gtk_widget_show (treeview5);
  gtk_fixed_put (GTK_FIXED (fixed15), treeview5, 8, 56);
  gtk_widget_set_size_request (treeview5, 976, 456);

  label238 = gtk_label_new ("");
  gtk_widget_show (label238);
  gtk_fixed_put (GTK_FIXED (fixed15), label238, 640, 496);
  gtk_widget_set_size_request (label238, 281, 41);

  modifier_ch = gtk_button_new ();
  gtk_widget_show (modifier_ch);
  gtk_fixed_put (GTK_FIXED (fixed15), modifier_ch, 208, 8);
  gtk_widget_set_size_request (modifier_ch, 130, 45);

  alignment50 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment50);
  gtk_container_add (GTK_CONTAINER (modifier_ch), alignment50);

  hbox50 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox50);
  gtk_container_add (GTK_CONTAINER (alignment50), hbox50);

  image53 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image53);
  gtk_box_pack_start (GTK_BOX (hbox50), image53, FALSE, FALSE, 0);

  label210 = gtk_label_new_with_mnemonic (_("MODIFIER"));
  gtk_widget_show (label210);
  gtk_box_pack_start (GTK_BOX (hbox50), label210, FALSE, FALSE, 0);

  supp_tree_ch = gtk_button_new ();
  gtk_widget_show (supp_tree_ch);
  gtk_fixed_put (GTK_FIXED (fixed15), supp_tree_ch, 344, 8);
  gtk_widget_set_size_request (supp_tree_ch, 122, 45);

  alignment51 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment51);
  gtk_container_add (GTK_CONTAINER (supp_tree_ch), alignment51);

  hbox51 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox51);
  gtk_container_add (GTK_CONTAINER (alignment51), hbox51);

  image54 = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image54);
  gtk_box_pack_start (GTK_BOX (hbox51), image54, FALSE, FALSE, 0);

  label211 = gtk_label_new_with_mnemonic (_("Supprimer "));
  gtk_widget_show (label211);
  gtk_box_pack_start (GTK_BOX (hbox51), label211, FALSE, FALSE, 0);

  label356 = gtk_label_new ("");
  gtk_widget_show (label356);
  gtk_fixed_put (GTK_FIXED (fixed15), label356, 704, 0);
  gtk_widget_set_size_request (label356, 289, 41);

  label367 = gtk_label_new_with_mnemonic (_("<b><span color=\"blue\"> Afficher</span></b>"));
  gtk_widget_show (label367);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 3), label367);
  gtk_label_set_use_markup (GTK_LABEL (label367), TRUE);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed16);

  treeview6 = gtk_tree_view_new ();
  gtk_widget_show (treeview6);
  gtk_fixed_put (GTK_FIXED (fixed16), treeview6, 40, 64);
  gtk_widget_set_size_request (treeview6, 352, 248);

  button56 = gtk_button_new_with_mnemonic (_("capture fumee"));
  gtk_widget_show (button56);
  gtk_fixed_put (GTK_FIXED (fixed16), button56, 352, 360);
  gtk_widget_set_size_request (button56, 128, 32);

  button57 = gtk_button_new_with_mnemonic (_("capture mouvement"));
  gtk_widget_show (button57);
  gtk_fixed_put (GTK_FIXED (fixed16), button57, 488, 360);
  gtk_widget_set_size_request (button57, 152, 32);

  label383 = gtk_label_new (_("<b><span color =\"blue\" >Capture</span></b>"));
  gtk_widget_show (label383);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 4), label383);
  gtk_label_set_use_markup (GTK_LABEL (label383), TRUE);

  buttonMaps = gtk_button_new ();
  gtk_widget_show (buttonMaps);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonMaps, 720, 160);
  gtk_widget_set_size_request (buttonMaps, 74, 29);

  alignment93 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment93);
  gtk_container_add (GTK_CONTAINER (buttonMaps), alignment93);

  hbox93 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox93);
  gtk_container_add (GTK_CONTAINER (alignment93), hbox93);

  image103 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image103);
  gtk_box_pack_start (GTK_BOX (hbox93), image103, FALSE, FALSE, 0);

  label384 = gtk_label_new_with_mnemonic (_("Maps"));
  gtk_widget_show (label384);
  gtk_box_pack_start (GTK_BOX (hbox93), label384, FALSE, FALSE, 0);

  buttonINST = gtk_button_new ();
  gtk_widget_show (buttonINST);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonINST, 800, 152);
  gtk_widget_set_size_request (buttonINST, 74, 41);

  image94 = create_pixmap (Gestion_foyer, "aaaaaaaaaaa.png");
  gtk_widget_show (image94);
  gtk_container_add (GTK_CONTAINER (buttonINST), image94);

  buttonFB = gtk_button_new ();
  gtk_widget_show (buttonFB);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonFB, 880, 160);
  gtk_widget_set_size_request (buttonFB, 75, 38);

  image93 = create_pixmap (Gestion_foyer, "button-facebookfinal.svg");
  gtk_widget_show (image93);
  gtk_container_add (GTK_CONTAINER (buttonFB), image93);

  image104 = create_pixmap (Gestion_foyer, "tof.png");
  gtk_widget_show (image104);
  gtk_fixed_put (GTK_FIXED (fixed4), image104, 1128, 192);
  gtk_widget_set_size_request (image104, 500, 600);

  image92 = create_pixmap (Gestion_foyer, "foooyer.png");
  gtk_widget_show (image92);
  gtk_fixed_put (GTK_FIXED (fixed4), image92, 0, 0);
  gtk_widget_set_size_request (image92, 1000, 200);

  g_signal_connect ((gpointer) ajou_ch, "clicked",
                    G_CALLBACK (on_ajou_ch_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5_ok_, "clicked",
                    G_CALLBACK (on_button5_ok__clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton12_poste, "toggled",
                    G_CALLBACK (on_radiobutton12_poste_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton11_poste, "toggled",
                    G_CALLBACK (on_radiobutton11_poste_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton15_groupe, "toggled",
                    G_CALLBACK (on_checkbutton15_groupe_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton14_groupe, "toggled",
                    G_CALLBACK (on_checkbutton14_groupe_toggled),
                    NULL);
  g_signal_connect ((gpointer) supp_ch, "clicked",
                    G_CALLBACK (on_supp_ch_clicked),
                    NULL);
  g_signal_connect ((gpointer) modi_ch, "clicked",
                    G_CALLBACK (on_modi_ch_clicked),
                    NULL);
  g_signal_connect ((gpointer) rech_ch, "clicked",
                    G_CALLBACK (on_rech_ch_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview5, "row_activated",
                    G_CALLBACK (on_treeview5_row_activated),
                    NULL);
  g_signal_connect ((gpointer) modifier_ch, "clicked",
                    G_CALLBACK (on_actua_ch_clicked),
                    NULL);
  g_signal_connect ((gpointer) supp_tree_ch, "clicked",
                    G_CALLBACK (on_supp_tree_ch_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview6, "row_activated",
                    G_CALLBACK (on_treeview6_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button56, "clicked",
                    G_CALLBACK (on_button56_clicked),
                    NULL);
  g_signal_connect ((gpointer) button57, "clicked",
                    G_CALLBACK (on_button57_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonMaps, "clicked",
                    G_CALLBACK (on_buttonMaps_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonINST, "clicked",
                    G_CALLBACK (on_buttonINST_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonFB, "clicked",
                    G_CALLBACK (on_buttonFB_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label379), entry19);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_foyer, Gestion_foyer, "Gestion_foyer");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, notebook3, "notebook3");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label279, "label279");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label337, "label337");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, ajou_ch, "ajou_ch");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image12, "image12");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label59, "label59");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button9, "button9");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment76, "alignment76");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox76, "hbox76");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image82, "image82");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label320, "label320");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, combobox6, "combobox6");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button7, "button7");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment78, "alignment78");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox78, "hbox78");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image85, "image85");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label357, "label357");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label333, "label333");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button8, "button8");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment80, "alignment80");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox80, "hbox80");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image87, "image87");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label359, "label359");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button13, "button13");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment81, "alignment81");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox81, "hbox81");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image88, "image88");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label360, "label360");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label334, "label334");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button10, "button10");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment79, "alignment79");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox79, "hbox79");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image86, "image86");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label358, "label358");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button12, "button12");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment83, "alignment83");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox83, "hbox83");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image90, "image90");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label362, "label362");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label338, "label338");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label335, "label335");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button11, "button11");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment82, "alignment82");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox82, "hbox82");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image89, "image89");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label361, "label361");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label336, "label336");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button17, "button17");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment84, "alignment84");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox84, "hbox84");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image91, "image91");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label363, "label363");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button14, "button14");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button15, "button15");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button16, "button16");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button19, "button19");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button18, "button18");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button5_ok_, "button5_ok_");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment59, "alignment59");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox59, "hbox59");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image62, "image62");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label237, "label237");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, radiobutton12_poste, "radiobutton12_poste");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, radiobutton11_poste, "radiobutton11_poste");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, checkbutton15_groupe, "checkbutton15_groupe");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, checkbutton14_groupe, "checkbutton14_groupe");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label364, "label364");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label83, "label83");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, supp_ch, "supp_ch");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image13, "image13");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label61, "label61");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label332, "label332");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button20, "button20");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment77, "alignment77");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox77, "hbox77");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image84, "image84");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label331, "label331");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label365, "label365");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, entry17, "entry17");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, entry18, "entry18");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, entry19, "entry19");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, entry20, "entry20");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, entry21, "entry21");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label84, "label84");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label317, "label317");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, modi_ch, "modi_ch");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image19, "image19");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label78, "label78");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button45, "button45");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, rech_ch, "rech_ch");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image15, "image15");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label64, "label64");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button53, "button53");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button52, "button52");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label354, "label354");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label355, "label355");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, combobox7, "combobox7");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button49, "button49");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment85, "alignment85");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox85, "hbox85");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image95, "image95");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label376, "label376");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button51, "button51");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment86, "alignment86");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox86, "hbox86");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image96, "image96");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label377, "label377");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button48, "button48");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment87, "alignment87");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox87, "hbox87");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image97, "image97");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label378, "label378");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button46, "button46");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment88, "alignment88");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox88, "hbox88");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image98, "image98");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label382, "label382");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button50, "button50");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment90, "alignment90");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox90, "hbox90");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image100, "image100");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label380, "label380");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button55, "button55");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment91, "alignment91");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox91, "hbox91");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image101, "image101");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label381, "label381");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button54, "button54");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment92, "alignment92");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox92, "hbox92");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image102, "image102");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label375, "label375");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label379, "label379");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label366, "label366");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, treeview5, "treeview5");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label238, "label238");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, modifier_ch, "modifier_ch");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment50, "alignment50");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox50, "hbox50");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image53, "image53");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label210, "label210");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, supp_tree_ch, "supp_tree_ch");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment51, "alignment51");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox51, "hbox51");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image54, "image54");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label211, "label211");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label356, "label356");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label367, "label367");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, treeview6, "treeview6");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button56, "button56");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, button57, "button57");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label383, "label383");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, buttonMaps, "buttonMaps");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, alignment93, "alignment93");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, hbox93, "hbox93");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image103, "image103");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, label384, "label384");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, buttonINST, "buttonINST");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image94, "image94");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, buttonFB, "buttonFB");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image93, "image93");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image104, "image104");
  GLADE_HOOKUP_OBJECT (Gestion_foyer, image92, "image92");

  return Gestion_foyer;
}

